services:
  - type: web
    name: kien-quoc-ky
    runtime: python
    buildCommand: pip install uv && uv sync
    startCommand: uv run fastapi run backend/main.py --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.14"
      - key: DEBUG
        value: "false"
    plan: free
    healthCheckPath: /health
